# Configuration for the VQE experiment

experiment_setup:
  name: "2Qubit_Ising_HardwareEfficient_GPU_Run"
  num_runs: 1

quantum_model:
  num_qubits: 2

backend_options:
  device: "cuda"

optimizer_params:
  name: "Adam"
  learning_rate: 0.1
  iterations: 100

analysis_params:
  exact_energy: -1.5

