# Configuration for the VQE experiment

experiment_setup:
  name: "2Qubit_Ising_HardwareEfficient_GPU_Run"
  num_runs: 10

quantum_model:
  num_qubits: 8

backend_options:
  device: "cpu"

optimizer_params:
  name: "Adam"
  learning_rate: 0.01
  iterations: 1000

analysis_params:
  exact_energy: -1.5

