# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_VQE_Experiment"
  num_runs: 4
  theta1_sample_rounds: 8
  gamma_sample_rounds: 2
  energy_sample_rounds: 32
  seed: 42

quantum_model:
  num_qubits: 4
  problem: "GHZ"
  classical_network:
    type: "SimpleNN"
  hamiltonian:
    global_term: 8
    perturb: 0.1

optimizer_params:
  name: "Adam"
  lr_theta1: 1.5e-2    # learning-rate for θ₁  (syndrome angles)
  lr_gamma: 6e-4      # learning-rate for γ   (MLP weights)
  iterations: 10
  decay:
    type: exponential      # 'exponential' | 'cosine' | 'none'
    decay_rate: 0.9       # factor applied every `decay_steps`
    decay_steps: 100       # how many weight-updates per decay
    staircase: false       # true → stepwise, false → smooth

precision:
  complex: complex64
  float: float32
  energy: float32
