# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_VQE_Experiment"
  num_runs: 10
  sample_rounds: 10

quantum_model:
  num_qubits: 4
  problem: "GHZ_tc"
  classical_network:
    type: "SimpleNN"
  hamiltonian:
    parameters:
      global_term: 1.0
      perturb: 0.1

optimizer_params:
  name: "Adam"
  learning_rate: 0.01
  iterations: 100


