# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_VQE_Experiment"
  num_runs: 4
  sample_rounds: 128

quantum_model:
  num_qubits: 4
  problem: "GHZ_tc"
  classical_network:
    type: "SimpleNN"
  hamiltonian:
    global_term: 4
    perturb: 0.1

optimizer_params:
  name: "Adam"
  lr_theta1: 1.0e-3     # learning-rate for θ₁  (syndrome angles)
  lr_gamma: 1.0e-6      # learning-rate for γ   (MLP weights)
  iterations: 100


