# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_VQE_Experiment"
  num_runs: 8
  sample_rounds: 128

quantum_model:
  num_qubits: 4
  problem: "GHZ_tc"
  classical_network:
    type: "SimpleNN"
  hamiltonian:
    global_term: 0
    perturb: 0.1

optimizer_params:
  name: "Adam"
  lr_theta1: 0.01    # learning-rate for θ₁  (syndrome angles)
  lr_gamma: 0.0001      # learning-rate for γ   (MLP weights)
  iterations: 1000
  decay:
    type: exponential      # 'exponential' | 'cosine' | 'none'
    decay_rate: 0.9       # factor applied every `decay_steps`
    decay_steps: 100       # how many weight-updates per decay
    staircase: false       # true → stepwise, false → smooth


