# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_NonSampling_VQE_Experiment"
  num_runs: 16
  sample_rounds: 128
  seed: 42

quantum_model:
  num_qubits: 4
  problem: "GHZ"
  hamiltonian:
    global_term: 8
    perturb: 0.1

optimizer_params:
  name: "Adam"
  learning_rate: 0.01
  iterations: 1000
  decay:
    type: exponential      # 'exponential' | 'cosine' | 'none'
    decay_rate: 0.9       # factor applied every `decay_steps`
    decay_steps: 100       # how many weight-updates per decay
    staircase: false       # true → stepwise, false → smooth

precision:
  complex: complex64
  float: float32
  energy: float32

