# Configuration for the VQE experiment

experiment_setup:
  name: "GHZ_UVQE_Experiment"
  num_runs: 8
  sample_rounds: 128

quantum_model:
  num_qubits: 4
  problem: "GHZ"
  hamiltonian:
    global_term: 0
    perturb: 0.1

optimizer_params:
  name: "Adam"
  learning_rate: 0.01
  iterations: 2000
  decay:
    type: exponential      # 'exponential' | 'cosine' | 'none'
    decay_rate: 0.9       # factor applied every `decay_steps`
    decay_steps: 100       # how many weight-updates per decay
    staircase: false       # true → stepwise, false → smooth


